name: 'Karate first test'
description: 'First trial'

# inputs:
#   input:
#     description: "first input"
#     required: true
#   secret:
#     description: "trying secret"
#     required: true

# outputs:
#   chart_name:
    description: "The name of the packaged Chart"
    value: ${{ steps.karate.outputs.outputprueba }}
outputs:
   fav-animal: 
      description: "The name of the packaged Chart"
      value: ${{steps.abc.outputs.FAV_ANIMAL}}
   fav-number:
      description: "The name of the packaged Chart"
      value: ${{steps.abc.outputs.FAV_NUMBER}}
runs:
  using: "composite"
  steps:
    - id: abc
      shell: bash
      run: |
        echo '::set-output name=FAV_NUMBER::3'
        echo '::set-output name=FAV_ANIMAL::tiger'
    - id: Read-output
      shell: bash
      run: |
        echo "${{steps.abc.outputs.FAV_NUMBER}}"
        echo "${{steps.abc.outputs.FAV_ANIMAL}}"



