name: 'Karate first test'
description: 'First trial'

# inputs:
#   input:
#     description: "first input"
#     required: true
#   secret:
#     description: "trying secret"
#     required: true

# outputs:
#   chart_name:
#     description: "The name of the packaged Chart"
#     value: ${{ steps.karate.outputs.prueba }}
    
runs:
  using: "composite"
  steps:
  - id: karatezero
    shell: bash
    run: chmod +x ${{ github.action_path }}/executablescript.sh
  - id: karateone
    shell: bash
    run: ${{ github.action_path }}/executablescript.sh
#   - id: karatedos
#     shell: bash
#     run: echo ${{ outputs.chart_name }}
