name: 'Karate first test'
description: 'First trial'

inputs:
  input:
    description: "first input"
    required: true
  secret:
    description: "trying secret"
    required: true


runs:
  using: "composite"
  steps:

  - run: echo {{ inputs.input }}
    shell: bash
  - run: echo {{ inputs.secret }}
    shell: bash
  - run: echo "hola ha funcionado"
    shell: bash
  - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
    shell: bash
  - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
    shell: bash
  - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
    shell: bash
  - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
    shell: bash
  - run: echo "🖥️ The workflow is now ready to test your code on the runner."
    shell: bash
  - name: List files in the repository
    shell: bash
    run: |
      ls ${{ github.workspace }}
  - run: echo "🍏 This job's status is ${{ job.status }}."
    shell: bash
  - id: karate
    shell: bash
    run: ${{ github.action_path }}/executablescript.sh

  - id: karatetwo
    shell: bash
    run: |
      chmod +x /home/runner/work/karate-simulator/karate-simulator/tests/thisisascript.sh
      sh /home/runner/work/karate-simulator/karate-simulator/tests/thisisascript.sh
