name: "Create temp directory"
description: "Action to create temp directory"

inputs:
  destination: 
    description: "Temp directory"
    required: false
  destfile: 
    description: "Temp directory"
    required: false

runs:
  using: "composite"
  steps:
    - id: create-temp-dir
      shell: bash
      run: |
        ${{ github.action_path }}/main.sh
    - id: create-temp-dir2
      shell: bash
      run: |
        cd ${{ github.action_path }}
        mkdir output
        pwd
        mkdir ${{inputs.destination}}/withdirectory
        ls -lart
        cd output
        touch foo.bar
     - id: create-temp-dir3
      shell: bash
      run: |
        echo "this is a line" > ${{inputs.destfile}}

#     - uses: actions/upload-artifact@v3
#        with:
#         name: output-archive
#         path: ./output
