name: "Create temp directory"
description: "Action to create temp directory"

# outputs:
#   temp_dir: 
#     description: "Temp directory"
#     value: ${{steps.create-temp-dir.outputs.temp_dir}}

runs:
  using: "composite"
  steps:
    - id: create-temp-dir
      shell: bash
      run: |
        ${{ github.action_path }}/main.sh
    - id: create-temp-dir2
      shell: bash
      run: |
        cd ${{ github.action_path }}
        mkdir output
        pwd
        ls -lart
        cd output
        touch foo.bar
#     - uses: actions/upload-artifact@v3
#        with:
#         name: output-archive
#         path: ./output
