name: Karate test

on:
  workflow_call:
  
env:
  CHECKING_DELETION: false
  check_if: false

jobs:

  # label of the container job
  checking-job:
    # containers must run in Linux based operating systems
    runs-on: ubuntu-latest
    # Docker Hub image that `postgres-job` executes in

    steps:
    
      - name: Checkout workflow repo
        uses: actions/checkout@v2
        with:
          repository: almudena-alvarez/composite-workflow-simulator
          ref: main
          path: workflow 

#       - name: Checking variable
#         shell: bash
#         run: |
#           cd ${{ github.workspace }}/workflow/scripts
#           sh ${{ github.workspace }}/workflow/scripts/checkvariable.sh
        
      - name: Checking variable1
        shell: bash
        if: ${{ env.CHECKING_DELETION }}
        run: |
          echo "passed"
          
      - name: Checking variable2
        shell: bash
        if: ${{ env.check_if }} == 'false'
        run: |
          echo "passed first if condition"
          
      - name: Checking variable3
        shell: bash
        if: ${{ env.check_if=='false'  }}
        run: |
          echo "passed second if condition"
          
      - name: Checking variable4
        shell: bash
        if: ${{ env.check_if }} == 'true' 
        run: |
          echo "passed third if condition"
          
      - name: Checking variable5
        shell: bash
        if: ${{ env.check_if=='true'  }}
        run: |
          echo "passed fourth if condition"
        
      - name: Checking variable6
        shell: bash
        run: |
          echo "jumped to the next one"
          
