name: composite

on:
    push:
      branches:
      - main

jobs:
  trial:
    name: job-name
    runs-on: ubuntu-latest
    outputs:
      pruebafinal: ${{ steps.id.outputs.chart_name }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: name
        id: id
        uses: ./.github/actions/database
#         with:
#           input: "this is the input"
#           secret: ${{ secrets.secret }}

  
  
