name: composite

on:
    push:
      branches:
      - main

jobs:
  trial:
    name: job-name
    runs-on: ubuntu-latest
    outputs:
        fav-animal: ${{steps.id.outputs.fav-animal}}
        fav-number: ${{steps.id.outputs.fav-number}}
        prueba: ${{steps.id.outputs.prueba}}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: name
        id: id
        uses: ./.github/actions/database
        with:
#           input: "this is the input"
          secret: ${{ secrets.SECRET }}
      - name: name
        id: test
        shell: bash
        run: |
            echo ${{ steps.id.outputs.fav-animal }}
            echo ${{ steps.id.outputs.fav-number }}
            echo ${{ steps.id.outputs.prueba }}

  
  
