name: Karate test

on:
  workflow_call:
    secrets:
      FIRST_SECRET:
        required: true


jobs:
  build:
    name: this is the name
    runs-on: ubuntu-latest
  
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "https://www.$FIRST_SECRET.es/"
      - name: script
        run: |
          chmod +x /home/runner/work/karate-simulator/karate-simulator/tests/thisisascript.sh
          sh /home/runner/work/karate-simulator/karate-simulator/tests/thisisascript.sh
        shell: bash
      - name: Checkout tools repo
        uses: actions/checkout@v3
        with:
          repository: almudena-alvarez/composite-workflow-simulator
          path: composite-branch
          
      - name: List files in the repository
        shell: bash
        run: |
          ls ${{ github.workspace }}
      - name: List files in the repository
        shell: bash
        run: |
          ls ${{ github.workspace }}/composite-branch
      - name: check composite
        id: composite
        uses: ./composite-branch/.github/actions/database
        with:
          FIRST_SECRET: ${{ secrets.FIRST_SECRET }}

