name: Karate test

on:
  workflow_call:
    secrets:
      FIRST_SECRET:
        required: true


jobs:
  build:
    name: this is the name
    runs-on: ubuntu-latest
  
    steps:

      - run: echo "https://www.$FIRST_SECRET.es/"
      - name: script
        run: |
          chmod +x /home/runner/work/karate-simulator/karate-simulator/tests/thisisascript.sh
          sh /home/runner/work/karate-simulator/karate-simulator/tests/thisisascript.sh
        shell: bash
      - name: check composite
        id: composite
        uses: ./.github/actions/database
        with:
          FIRST_SECRET: ${{ secrets.FIRST_SECRET }}
          repository: oasis-cib
          version: ${{ steps.define-version.outputs.build_version }}

