name: Karate test

on:
  workflow_call:
    secrets:
      FIRST_SECRET:
        required: true


jobs:
  build:
    name: workflow repo
    runs-on: ubuntu-latest
  
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          path: karate

          
      - name: 1List files in the repository
        shell: bash
        run: |
          ls ${{ github.workspace }}
          

      - name: Checkout karate repo
        uses: actions/checkout@v2
        with:
          repository: almudena-alvarez/composite-workflow-simulator
          ref: composite-branch
          path: wworkflow     
          
      - name: 1List files in the repository
        shell: bash
        run: |
          ls -l ${{ github.workspace }}/wworkflow/.github/actions/database

#       - run: echo "https://www.$FIRST_SECRET.es/"
      - name: script
        run: |
          chmod +x ${{ github.workspace }}/wworkflow/.github/actions/database/executablescript.sh
          sh ${{ github.workspace }}/wworkflow/.github/actions/database/executablescript.sh
        shell: bash
#       - name: Checkout tools repo
#         uses: actions/checkout@v3
#         with:
#           repository: almudena-alvarez/composite-workflow-simulator
#           path: /.github
          
#       - name: 4List files in the repository
#         shell: bash
#         run: |
#           ls ${{ github.workspace }}
#       - name: 5List files in the repository
#         shell: bash
#         run: |
#           ls ${{ github.workspace }}/actions
#       - name: 5List files in the repository
#         shell: bash
#         run: |
#           ls ${{ github.workspace }}/actions/database
#       - name: 6List files in the repository
#         shell: bash
#         run: |
#           ls -l
#           dir
#       - name: check composite
#         id: composite
#         uses: ${{ github.workspace }}/workflow/.github/actions/database
#         with:
#           FIRST_SECRET: ${{ secrets.FIRST_SECRET }}

