name: Karate test

on:
  workflow_call:
    secrets:
      FIRST_SECRET:
        required: true


jobs:
  build:
    name: workflow repo
    runs-on: ubuntu-latest
  
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          path: main
          
      - name: 1List files in the repository
        shell: bash
        run: |
          ls ${{ github.workspace }}
          
      - name: 2List files in the repository
        shell: bash
        run: |
          ls ${{ github.workspace }}/main
          
          
      - name: 3List files in the repository
        shell: bash
        run: |
          ls -l main
          dir
#       - run: echo "https://www.$FIRST_SECRET.es/"
#       - name: script
#         run: |
#           chmod +x /home/runner/work/karate-simulator/karate-simulator/tests/thisisascript.sh
#           sh /home/runner/work/karate-simulator/karate-simulator/tests/thisisascript.sh
#         shell: bash
      - name: Checkout tools repo
        uses: actions/checkout@v3
        with:
          repository: almudena-alvarez/composite-workflow-simulator
          path: composite
          
      - name: 4List files in the repository
        shell: bash
        run: |
          ls ${{ github.workspace }}
      - name: 5List files in the repository
        shell: bash
        run: |
          ls ${{ github.workspace }}/composite/.github
      - name: 6List files in the repository
        shell: bash
        run: |
          ls -l
          dir
      - name: check composite
        id: composite
        uses: ./composite/.github/actions/database
        with:
          FIRST_SECRET: ${{ secrets.FIRST_SECRET }}

